### ISSUE TITLE
Feature request: Expand capability of `network_p2p()`

### ISSUE THREAD

**Issue by dehaozhang15** [microsoft/wpa#109]
I think having the ability to integrate 'modularity' function with the existing 'network_p2p' function would generate greater utilities when analyzing the strength of a community's network cohesion. Currently the membership vector need to be created manually and passed in the 'modularity' function. Besides, this vector needs to be numeric, so if it is possible to implicitly convert 'hrvar' into numeric vectors in order to compute the modularity score, it would be great.

**Comment by dehaozhang15** [comment]
As a add-on comment, integrating "density score" or "density ratio" (compare actual shared connections against expected number of connections in that team size) into 'network_p2p' can also be good to expand capabilities in team cohesion analysis. Not sure if this should be a separate feature request...

**Comment by martinctc** [comment]
These are great suggestions @dehaozhang15, thanks! Computing this will not be a problem, the only question is whether it will be easier for (i) the user to export it directly from the function (as another option passed to `"return"`), or (ii) request the user to pipe the function through another separate function that calculates those scores from a clustered network. For instance:

```R
# Modularity
sim_data %>%
  network_p2p(display = "leiden",
                        return = "network") %>%
  compute_modularity()
  
# Density Score
sim_data %>%
  network_p2p(display = "leiden",
                        return = "network") %>%
  compute_density()  
```
I prefer some version of the latter because it makes more sense performance-wise, as people are unlikely to want to export **only** the modularity score without some other output. This latter approach also makes the debugging process easier overall. It's one extra line of code for the user, which we can provide more examples in the documentation to make sure users are aware of this feature. What do we think about this approach?

**Comment by martinctc** [comment]
For reference, here is the current workaround for calculating modularity: 

```R
# Load packages
library(wpa)
library(tidyverse)

# Simulate data
p2p_data <- p2p_data_sim()

# Return igraph object
# Return Louvain clusters
p2p_ig <- 
  p2p_data %>%
  network_p2p(
    display = "louvain",
    return = "network"
  )

# Get membership
# Must be a numeric vector
mem_id <- igraph::get.vertex.attribute(p2p_ig, name = "cluster")

# Compute modularity score
p2p_ig %>%
  igraph::modularity(
    membership = mem_id
    )
```
In a summary, you export the 'igraph' object and use igraph's own functions to manipulate the object to get to the modularity scores.
