### ISSUE TITLE
Feature request: include meetings and unscheduled calls signals in `flex_index()`

### ISSUE THREAD

**Issue by Staceyun** [microsoft/wpa#183]
**Is your feature request related to a problem? Please describe.**
Meetings and unscheduled calls, apart from emails and IMs, are critical components to understand user collaboration behaviors and are suggested to be added to the flexibility index analysis.

**Describe the solution you'd like**
Have meetings and unscheduled calls included in the signal extraction. For example, enable users to write, signals = c("email", "IM", "Meetings", "Unscheduled_calls") and extract signals accordingly.

**Comment by martinctc** [comment]
Thanks @Staceyun! Meetings and unscheduled calls were initially omitted because of the high likelihood of false positives (e.g. meetings accepted but not attended) compared to actual emails/IMs sent. However, we want to provide options for users so we will be implementing this - targeting for patch version `v1.6.2`.
