### ISSUE TITLE
Refactor: simplify API so that `network_p2p()` can handle community detection

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#38]
Currently the network visualizations that come from a p2p query are handled by a variety of functions. It would be best to have a single function (`network_p2p`) acting as a wrapper, with a range of visualization options as parameters (e.g. can color code nodes with both hr attributes or using a community detection algo) 

For example:

Default behavior, displays network plot with nodes colored by Organization:
```R
network_p2p(display="hrvar", hrvar="Organization", return="plot",  path=NULL)
```

Option to color code the nodes as a different hrvar:
```R
network_p2p(display="hrvar", hrvar="LevelDesignation")
```

Option to color code the nodes using a Louvain community detection algorithm: 
```R
network_p2p(display="clusters", mode="louvain", return="plot")
```

**Comment by martinctc** [comment]
This is a great suggestion @moralec. I've classified this as a **spike** because there are a few things to consider when combining / wrapping the functions:

1.  `network_leiden()` and `network_louvain()` has a "describe" option which returns a list of community descriptions. This option will not be relevant for a simple `network_p2p()` plot. If this combination is activated, we need to return an informative error message. 

2. The two community detection functions make use of two plotting methods depending on the size of the data (**ggraph** and "base" **igraph**). 

3. Minimise code duplication. The final result should have the minimal amount of duplicate code. Currently, the duplication occurs in the plotting options, where you can create an "hrvar" network plot in either `network_p2p()`, `network_leiden()`, and `network_louvain()`. 

4. Optimise performance. Performance is particularly important with person to person networks due to the large number of nodes and edges. Functions will become impractical for exploratory analysis if they take over 5 minutes to run. The new design needs to be done in such a way that no additional calculations take place if the output isn't "requested" by the user. 

5. Smart path return. At the moment, there is a `path` return for the three functions, with different defaults. There should be a smart path return capability where the default file name returned provides the most useful information, e.g. community detection method, time stamp, size, etc. 

6. Default node placement algorithm. I propose we use "mds" for all three methods, since this would be deterministic, i.e. same placements every time we run it. 

More suggestions / thoughts welcome!
