### ISSUE TITLE
Bug: `create_dist()` assume metric is in hours

### ISSUE THREAD

**Issue by moralec** [microsoft/wpa#77]
**Describe the bug**
When you create a custom dist with Create_Dist, the labels show "hours", even if you are 

**To Reproduce**

```R
sq_data %>% select("PersonId", "Date", "Meetings_with_manager_1_on_1", "Organization") %>% group_by(PersonId)  %>% mutate(total=sum(Meetings_with_manager_1_on_1), weeks=n())  %>% mutate(Frequency_of_1_on_1_with_manager = (1 - (total/weeks))) %>%  create_dist(metric="Frequency_of_1_on_1_with_manager", hrvar="Organization", cut = c(.1, .25, 5))
```

![wpa export 20210218_151307](https://user-images.githubusercontent.com/62895857/108377303-cfaec700-71fb-11eb-9694-b58666a79041.png)

**Comment by martinctc** [comment]
Thanks @moralec! `create_dist()` currently has an argument called `unit` that allows users to specify a string for whether the unit should show as hours or minutes: https://github.com/microsoft/wpa/blob/main/R/create_dist.R

```R
create_dist <- function(data,
                        metric,
                        hrvar = "Organization",
                        mingroup = 5,
                        return = "plot",
                        cut = c(15, 20, 25),
                        dist_colours = c("#facebc",
                                         "#fcf0eb",
                                         "#b4d5dd",
                                         "#bfe5ee"),
                        unit = "hours") {
```
This is in turn fed into [`cut_hour()`](https://github.com/microsoft/wpa/blob/main/R/cut_hour.R) to cut the numeric variable into categories. Would this work for your use case? If yes, we can perhaps improve the documentation so that it is clear to the user that the categories can be expressed in minutes as well.
